apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-hello-svc
  labels:
    app: grpc-hello-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-hello-svc
  template:
    metadata:
      labels:
        app: grpc-hello-svc
    spec:
      containers:
        - name: grpc-hello-svc
          image: hello-svc:v1.0
          ports:
            - containerPort: 50051
              name: grpc
            - containerPort: 8090
              name: metrics
          env:
            - name: PORT
              value: "50051"
          # requests资源请求和limits资源限制
          resources:
            requests:
              memory: "128Mi" # 容器启动时为其预留128兆字节的内存
              cpu: "100m" # 容器启动时为其预留0.1个CPU核心
            limits:
              memory: "256Mi" # 容器最多可以使用256兆字节内存
              cpu: "200m" # 容器最多可以使用0.2个CPU核心，超过会被限制使用
