apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-hello-svc
  labels:
    app: grpc-hello-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-hello-svc
  template:
    metadata:
      labels:
        app: grpc-hello-svc
    spec:
      containers:
        - name: grpc-hello-svc
          image: hello-svc:v1.0
          ports:
            - containerPort: 50051
              name: grpc
            - containerPort: 8090
              name: metrics
          env:
            - name: PORT
              value: "50051"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
