apiVersion: v1
kind: Service
metadata:
  name: grpc-hello-svc # 服务名
  labels:
    app: grpc-hello-svc
spec:
  clusterIP: None  # 关键配置：定义为Headless Service
  selector:
    app: grpc-hello-svc  # 匹配Deployment中的Pod标签
  ports:
    - name: grpc
      protocol: TCP
      port: 50051      # Service端口
      targetPort: 50051 # Pod端口
    - name: metrics
      protocol: TCP
      port: 8090      # metrics端口
      targetPort: 8090 # Pod端口
  publishNotReadyAddresses: true  # 发布未就绪的Pod地址
